// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package api

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	storage "github.com/exiffM/otus_homework/hw12_13_14_15_calendar/internal/storage"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDafff8e6DecodeHw12131415CalendarInternalServerHttpApiDefault(in *jlexer.Lexer, out *EventsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Method":
			out.Method = string(in.String())
		case "Error":
			out.Error = string(in.String())
		case "Data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]storage.Event, 0, 0)
					} else {
						out.Data = []storage.Event{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v1 storage.Event
					(v1).UnmarshalEasyJSON(in)
					out.Data = append(out.Data, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDafff8e6EncodeHw12131415CalendarInternalServerHttpApiDefault(out *jwriter.Writer, in EventsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Method\":"
		out.RawString(prefix[1:])
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"Error\":"
		out.RawString(prefix)
		out.String(string(in.Error))
	}
	{
		const prefix string = ",\"Data\":"
		out.RawString(prefix)
		if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Data {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EventsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDafff8e6EncodeHw12131415CalendarInternalServerHttpApiDefault(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EventsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDafff8e6EncodeHw12131415CalendarInternalServerHttpApiDefault(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EventsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDafff8e6DecodeHw12131415CalendarInternalServerHttpApiDefault(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EventsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDafff8e6DecodeHw12131415CalendarInternalServerHttpApiDefault(l, v)
}
func easyjsonDafff8e6DecodeHw12131415CalendarInternalServerHttpApiDefault1(in *jlexer.Lexer, out *EventResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Method":
			out.Method = string(in.String())
		case "Error":
			out.Error = string(in.String())
		case "Data":
			(out.Data).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDafff8e6EncodeHw12131415CalendarInternalServerHttpApiDefault1(out *jwriter.Writer, in EventResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Method\":"
		out.RawString(prefix[1:])
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"Error\":"
		out.RawString(prefix)
		out.String(string(in.Error))
	}
	{
		const prefix string = ",\"Data\":"
		out.RawString(prefix)
		(in.Data).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EventResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDafff8e6EncodeHw12131415CalendarInternalServerHttpApiDefault1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EventResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDafff8e6EncodeHw12131415CalendarInternalServerHttpApiDefault1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EventResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDafff8e6DecodeHw12131415CalendarInternalServerHttpApiDefault1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EventResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDafff8e6DecodeHw12131415CalendarInternalServerHttpApiDefault1(l, v)
}
func easyjsonDafff8e6DecodeHw12131415CalendarInternalServerHttpApiDefault2(in *jlexer.Lexer, out *DefaultResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Method":
			out.Method = string(in.String())
		case "Error":
			out.Error = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDafff8e6EncodeHw12131415CalendarInternalServerHttpApiDefault2(out *jwriter.Writer, in DefaultResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Method\":"
		out.RawString(prefix[1:])
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"Error\":"
		out.RawString(prefix)
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DefaultResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDafff8e6EncodeHw12131415CalendarInternalServerHttpApiDefault2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DefaultResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDafff8e6EncodeHw12131415CalendarInternalServerHttpApiDefault2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DefaultResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDafff8e6DecodeHw12131415CalendarInternalServerHttpApiDefault2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DefaultResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDafff8e6DecodeHw12131415CalendarInternalServerHttpApiDefault2(l, v)
}
