version: "3.9"

services:
  postgresqldb:
    image: postgres:13.3
    container_name: postgres
    hostname: postgresqldb
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: calendardb
      POSTGRES_USER: igor
      POSTGRES_PASSWORD: igorpwd
      POSTGRES_PORT: 5432
    networks:
      - calendar

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    depends_on:
      - postgresqldb
    ports:
      - 5672:5672
    networks:
      - calendar
  
  goose:
    build:
      context: ../
      dockerfile: ./migrations/Dockerfile
    depends_on:
      - postgresqldb
    command: sh -c './wait-for.sh postgresqldb:5432 -- goose postgres "postgres://igor:igorpwd@postgresqldb:5432/calendardb?sslmode=disable" up'
    networks:
      - calendar    

  calendar:
    build:
      context: ../
      dockerfile: ./build/calendar/Dockerfile
    depends_on:
      - postgresqldb
      - rabbitmq
    ports: 
      - 5000:5000
      - 1235:1235
    container_name: calendar
    environment:
      - DATABASE_HOST=postgresqldb
      - HOST=calendar
    networks:
      - calendar

  scheduler:
    build:
      context: ../
      dockerfile: ./build/scheduler/Dockerfile
    depends_on:
      - calendar
      - rabbitmq
    command: sh -c './opt/scheduler/wait-for.sh rabbitmq:5672 -- ./opt/scheduler/scheduler-app -config /etc/scheduler/schedulercfg.yml' 
    container_name: scheduler
    environment:
      - CALENDAR_HOST=calendar
      - RABBIT_HOST=amqp://guest:guest@rabbitmq:5672/
    networks:
      - calendar

  sender:
    build:
      context: ../
      dockerfile: ./build/sender/Dockerfile
    depends_on:
      scheduler:
        condition: service_started
    command: sh -c './opt/sender/wait-for.sh rabbitmq:5672 -- ./opt/sender/sender-app -config /etc/sender/sendercfg.yml' 
    container_name: sender
    environment:
      - RABBIT_HOST=amqp://guest:guest@rabbitmq:5672/
    networks:
      - calendar

networks:
  calendar: