logger:
  level: error
http:
  host: localhost
  port: 1235
  readheadertimeout: 10
rpc:
  host: localhost
  port: 5000
storage:
  type: database #local
  dsn: "user=igor dbname=calendardb password=igor" #"" #for local - empty