// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/EventService.proto

package eventrpcapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aca917489f88b51, []int{0}
}

func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (m *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(m, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

type Event struct {
	Id                   int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tittle               string                 `protobuf:"bytes,2,opt,name=tittle,proto3" json:"tittle,omitempty"`
	Start                *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	Duration             int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Description          string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Notification         int32                  `protobuf:"varint,6,opt,name=notification,proto3" json:"notification,omitempty"`
	Scheduled            bool                   `protobuf:"varint,7,opt,name=scheduled,proto3" json:"scheduled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aca917489f88b51, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Event) GetTittle() string {
	if m != nil {
		return m.Tittle
	}
	return ""
}

func (m *Event) GetStart() *timestamppb.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Event) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetNotification() int32 {
	if m != nil {
		return m.Notification
	}
	return 0
}

func (m *Event) GetScheduled() bool {
	if m != nil {
		return m.Scheduled
	}
	return false
}

type Error struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aca917489f88b51, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Id struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aca917489f88b51, []int{3}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Null)(nil), "calendar.Null")
	proto.RegisterType((*Event)(nil), "calendar.Event")
	proto.RegisterType((*Error)(nil), "calendar.Error")
	proto.RegisterType((*Id)(nil), "calendar.Id")
}

func init() {
	proto.RegisterFile("api/EventService.proto", fileDescriptor_4aca917489f88b51)
}

var fileDescriptor_4aca917489f88b51 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xbd, 0xae, 0xd3, 0x30,
	0x14, 0x26, 0xe1, 0x26, 0xb4, 0x27, 0xd5, 0x05, 0x59, 0x57, 0x55, 0x14, 0x40, 0x44, 0x99, 0x32,
	0x39, 0xf7, 0x16, 0x31, 0x31, 0xf1, 0xd3, 0xa1, 0x4b, 0x87, 0x14, 0x16, 0x36, 0x37, 0x3e, 0x2d,
	0x96, 0xdc, 0xd8, 0x72, 0x9c, 0x4a, 0x3c, 0x28, 0x0f, 0xc0, 0x9b, 0xa0, 0xda, 0x84, 0xfe, 0x50,
	0x06, 0xd8, 0xf2, 0x7d, 0xfe, 0x7e, 0xe2, 0x73, 0x0c, 0x53, 0xa6, 0x45, 0x35, 0xdf, 0x63, 0x6b,
	0x57, 0x68, 0xf6, 0xa2, 0x41, 0xaa, 0x8d, 0xb2, 0x8a, 0x8c, 0x1a, 0x26, 0xb1, 0xe5, 0xcc, 0x64,
	0xaf, 0xb6, 0x4a, 0x6d, 0x25, 0x56, 0x8e, 0x5f, 0xf7, 0x9b, 0xca, 0x8a, 0x1d, 0x76, 0x96, 0xed,
	0xb4, 0x97, 0x66, 0xcf, 0x2f, 0x05, 0xb8, 0xd3, 0xf6, 0x9b, 0x3f, 0x2c, 0x62, 0xb8, 0x59, 0xf6,
	0x52, 0x16, 0x3f, 0x02, 0x88, 0x5c, 0x0d, 0xb9, 0x85, 0x50, 0xf0, 0x34, 0xc8, 0x83, 0x32, 0xaa,
	0x43, 0xc1, 0xc9, 0x14, 0x62, 0x2b, 0xac, 0x95, 0x98, 0x86, 0x79, 0x50, 0x8e, 0xeb, 0x5f, 0x88,
	0xdc, 0x43, 0xd4, 0x59, 0x66, 0x6c, 0xfa, 0x38, 0x0f, 0xca, 0x64, 0x96, 0x51, 0x5f, 0x43, 0x87,
	0x1a, 0xfa, 0x69, 0xf8, 0x8f, 0xda, 0x0b, 0x49, 0x06, 0x23, 0xde, 0x1b, 0x66, 0x85, 0x6a, 0xd3,
	0x1b, 0x97, 0xff, 0x1b, 0x93, 0x1c, 0x12, 0x8e, 0x5d, 0x63, 0x84, 0x76, 0xc7, 0x91, 0xab, 0x3a,
	0xa5, 0x48, 0x01, 0x93, 0x56, 0x59, 0xb1, 0x11, 0x8d, 0x4f, 0x88, 0x5d, 0xc2, 0x19, 0x47, 0x5e,
	0xc0, 0xb8, 0x6b, 0xbe, 0x22, 0xef, 0x25, 0xf2, 0xf4, 0x49, 0x1e, 0x94, 0xa3, 0xfa, 0x48, 0x14,
	0x2f, 0x21, 0x9a, 0x1b, 0xa3, 0x0c, 0xb9, 0x83, 0x08, 0x0f, 0x1f, 0xee, 0x96, 0xe3, 0xda, 0x83,
	0xe2, 0x0e, 0xc2, 0x05, 0xbf, 0xbc, 0xfe, 0xec, 0x7b, 0x08, 0x93, 0xd3, 0xf9, 0x93, 0x07, 0x48,
	0x3e, 0x18, 0x64, 0x16, 0xfd, 0xb8, 0x9e, 0xd2, 0x61, 0x13, 0xd4, 0x11, 0xd9, 0x25, 0x51, 0x3c,
	0x22, 0x14, 0x92, 0x15, 0x4a, 0x6c, 0xac, 0xb7, 0x4c, 0x8e, 0x8a, 0x05, 0xbf, 0xa6, 0x7f, 0x80,
	0xe4, 0xb3, 0xe6, 0xff, 0x54, 0xf1, 0x06, 0x92, 0x8f, 0x28, 0x71, 0xb0, 0x9c, 0x57, 0x4c, 0xff,
	0xd8, 0xcd, 0xfc, 0xf0, 0x04, 0x9c, 0x2d, 0x76, 0x86, 0x8e, 0xfc, 0x45, 0x73, 0xa5, 0xeb, 0x3e,
	0x20, 0xef, 0x80, 0x2c, 0x95, 0x5d, 0x0d, 0x93, 0xfd, 0x8f, 0x88, 0xf7, 0xcf, 0xbe, 0xdc, 0xd2,
	0xea, 0x2d, 0x1e, 0xb0, 0xd1, 0x0d, 0xd3, 0x62, 0x1d, 0x3b, 0xdb, 0xeb, 0x9f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x67, 0xcd, 0x1f, 0xa0, 0xf3, 0x02, 0x00, 0x00,
}
